### ISSUE TITLE
Minecraft Crash With Fabric API0.40.0

### ISSUE THREAD

**Issue by lostopkk** [TheIllusiveC4/Somnus#5]
this issue https://github.com/FabricMC/fabric/issues/1697

**Comment by TheIllusiveC4** [comment]
You need to update to Somnus to the latest version, which was made to be compatible with Fabric API 0.39.0+. In addition, any mod that uses Somnus also needs to update or remove Somnus as a dependency altogether.

**Comment by lostopkk** [comment]
thank you very much for the quick reply
